version: "3.7"

services:
  chinexboroja:
    build: .
    environment:
      - DB_URL=jdbc:postgresql://db:5432/middevhashdb
      - DB_USER=root
      - DB_PASS=root
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - db

  db:
    image: postgres:16.1
    container_name: db
    environment:
      - POSTGRES_DB=middevhashdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432


  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:4.23
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 5050:80